# frontend/Dockerfile

# Base image for Node.js
FROM node:26-alpine

# Set the working directory inside the container
WORKDIR /app

# Expose the default Vite port
EXPOSE 5173

# Start the Vue development server
CMD ["npm", "run", "dev"]